# Numpy

## Basic Indexing and Operations

In [3]:
import numpy as np

# create arrays ---------------------------
a1 = np.array([0,1,2,3,4,5])
a2 = np.arange(6)

print('a1:', a1, ', shape:', a1.shape)
print('a2:', a2, ', shape:', a2.shape)
print('is a1 equal to a2? -->', a1 == a2)

a1: [0 1 2 3 4 5] , shape: (6,)
a2: [0 1 2 3 4 5] , shape: (6,)
is a1 equal to a2? --> [ True  True  True  True  True  True]


In [5]:
# create array ---------------------------
a1 = np.array([[1,2,3],[4,5,6]])

# operations -----------------------------
a2 = a1 * -1
a_add = a1 + a2
a_mul = a1 * a2
a_matmul = np.matmul(a1,a2.T)

print('a1:\n', a1, ', shape:', a1.shape, '\n')
print('a2:\n', a2, ', shape:', a2.shape, '\n')
print('a_add:\n', a_add, ', shape:', a_add.shape, '\n')
print('a_mul:\n', a_mul, ', shape:', a_mul.shape, '\n')
print('a_matmul:\n', a_matmul, ', shape:', a_matmul.shape, '\n')

a1:
 [[1 2 3]
 [4 5 6]] , shape: (2, 3) 

a2:
 [[-1 -2 -3]
 [-4 -5 -6]] , shape: (2, 3) 

a_add:
 [[0 0 0]
 [0 0 0]] , shape: (2, 3) 

a_mul:
 [[ -1  -4  -9]
 [-16 -25 -36]] , shape: (2, 3) 

a_matmul:
 [[-14 -32]
 [-32 -77]] , shape: (2, 2) 



In [9]:
# ones & zeros --------------------------
a1 = np.ones((5,2))
a2 = np.zeros((5,2))

# concatente/stack ----------------------
a_concat = np.concatenate([a1,a2], axis=-1)
a_stack = np.stack([a1,a2], axis=-1) # stacking column-wise when axis=-1

print('a_concat:\n', a_concat, ', shape:', a_concat.shape, '\n')
print('a_stack:\n', a_stack, ', shape:', a_stack.shape)

a_concat:
 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]] , shape: (5, 4) 

a_stack:
 [[[1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]]] , shape: (5, 2, 2)


In [26]:
# create array ------------------------
a1 = np.arange(12)
print('a1:\n', a1, ', shape:', a1.shape, '\n')

# reshape -----------------------------
a1 = a1.reshape((3,2,2))
print('a1:\n', a1, ', shape:', a1.shape, '<-- reshaping a1', '\n')

# index -------------------------------
a1[0] *= -1
print('a1:\n', a1, ', shape:', a1.shape, '<-- multiplying first array in a1 by -1', '\n')

a1[-1,0] *= -1
print('a1:\n', a1, ', shape:', a1.shape, '<-- multiplying last array, first row in a1 by -1', '\n')

a2 = a1[1:]
print('a2:\n', a2, ', shape:', a2.shape, '<-- extracting all arrays in a1 except for first one', '\n')

a3 = a1[:-1,:,0]
print('a3:\n', a3, ', shape:', a3.shape, '<-- extracting first column in all arrays in a1 except for last one', '\n')

a1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11] , shape: (12,) 

a1:
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]] , shape: (3, 2, 2) <-- reshaping a1 

a1:
 [[[ 0 -1]
  [-2 -3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]] , shape: (3, 2, 2) <-- multiplying first array in a1 by -1 

a1:
 [[[ 0 -1]
  [-2 -3]]

 [[ 4  5]
  [ 6  7]]

 [[-8 -9]
  [10 11]]] , shape: (3, 2, 2) <-- multiplying last array, first row in a1 by -1 

a2:
 [[[ 4  5]
  [ 6  7]]

 [[-8 -9]
  [10 11]]] , shape: (2, 2, 2) <-- extracting all arrays in a1 except for first one 

a3:
 [[ 0 -2]
 [ 4  6]] , shape: (2, 2) <-- extracting first column in all arrays in a1 except for last one 



## Advanced Indexing and Operations

In [25]:
# create array ----------------------
a = np.arange(8).reshape((2,2,2))
print('a:\n', a, ', shape:', a.shape, '\n')

a1 = a[[0,1],[1,0]] 
print('a1:\n', a1, ', shape:', a1.shape, '<-- first array - second row, second array - first row', '\n')

idxs = np.array([[0,1],[1,0]])
a2 = a[idxs]
print('a2:\n', a2, ', shape:', a2.shape, ', idxs shape:', idxs.shape,
      '\n             <-- first array - second array, second array - first array')

a3 = a[idxs, idxs]
print('a3:\n', a3, ', shape:', a3.shape, '<-- first array - first row, second array - second row,', '\n'
      '          second array - second row, first array - first row, \n')

a:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] , shape: (2, 2, 2) 

a1:
 [[2 3]
 [4 5]] , shape: (2, 2) <-- first array - second row, second array - first row 

a2:
 [[[[0 1]
   [2 3]]

  [[4 5]
   [6 7]]]


 [[[4 5]
   [6 7]]

  [[0 1]
   [2 3]]]] , shape: (2, 2, 2, 2) , idxs shape: (2, 2) 
             <-- first array - second array, second array - first array
a3:
 [[[0 1]
  [6 7]]

 [[6 7]
  [0 1]]] , shape: (2, 2, 2) <-- first array - first row, second array - second row, 
          second array - second row, first array - first row, 



In [28]:
a = np.random.randint(low=-2, high=2, size=(3,3,2)).astype(np.float)
print('a:\n', a, ', shape:', a.shape, '\n')

m = np.mean(a)
print('total mean of a before NaN substitution -->', np.around(m, decimals=2), '\n')

m_ax = np.mean(a, axis=1)
print('mean along second axis of a before NaN substitution -->\n', 
      np.around(m_ax, decimals=2), ', shape:', m_ax.shape, '\n')

print('\n', '----------------------------------------------------------------', ' \n')

a[a==0] = np.nan
print('a:\n', a, ', shape:', a.shape, '<-- substituting zero with NaN', '\n')

m = np.nanmean(a)
print('total mean of a after NaN substitution -->', np.around(m, decimals=2), '\n')

m_ax = np.nanmean(a, axis=1)
print('mean along second axis of a after NaN substitution -->\n', 
      np.around(m_ax, decimals=2), ', shape:', m_ax.shape, '\n')

a:
 [[[-2. -1.]
  [-1.  0.]
  [-1. -1.]]

 [[ 1. -1.]
  [-1.  1.]
  [ 0.  1.]]

 [[ 1. -2.]
  [ 1.  1.]
  [ 0. -2.]]] , shape: (3, 3, 2) 

total mean of a before NaN substitution --> -0.33 

mean along second axis of a before NaN substitution -->
 [[-1.33 -0.67]
 [ 0.    0.33]
 [ 0.67 -1.  ]] , shape: (3, 2) 


 ----------------------------------------------------------------  

a:
 [[[-2. -1.]
  [-1. nan]
  [-1. -1.]]

 [[ 1. -1.]
  [-1.  1.]
  [nan  1.]]

 [[ 1. -2.]
  [ 1.  1.]
  [nan -2.]]] , shape: (3, 3, 2) <-- substituting zero with NaN 

total mean of a after NaN substitution --> -0.4 

mean along second axis of a after NaN substitution -->
 [[-1.33 -1.  ]
 [ 0.    0.33]
 [ 1.   -1.  ]] , shape: (3, 2) 



## Vectorization and Broadcasting

In [30]:
def mul_fl(x, y):
    '''
    Input:
        x: (m,)
        y: (n)
    Output:
        result: (m,n)
    '''
    
    m, n = len(x), len(y)
    result = np.zeros((m,n))
    
    for x_idx, ex in enumerate(x):
        for y_idx, ey in enumerate(y):
            result[x_idx,y_idx] = ex * ey
            
    return result


def mul_vec(x, y):
    '''
    Input:
        x: (m,)
        y: (n)
    Output:
        result: (m,n)
    '''
    
    result = x[:,np.newaxis] * y
    
    return result
    

In [31]:
import time

# create arrays --------------------------------
x = np.ones(1000) * 2
y = np.ones(2000) * 3

# multiplication using for loops ---------------
start = time.time() # start timing
mul_result = mul_fl(x, y)
end = time.time() # end timing
print('time needed for element-wise multiplication using for loop:', end - start)

# multiplication using vectorization -----------
start = time.time() # start timing
mul_result = mul_vec(x, y)
end = time.time() # end timing
print('time needed for element-wise multiplication using vectorization:', end - start)


time needed for element-wise multiplication using for loop: 0.8390688896179199
time needed for element-wise multiplication using vectorization: 0.010178327560424805


#### Another example

In [33]:
# create arrays -------------------------------
x = np.ones((10,3)) * 2
y = np.ones((10,2)) * 3

# vectorizatiion ------------------------------
mul_result = x[:,:,np.newaxis] * y[:,np.newaxis,:]
print('mul_result shape =', mul_result.shape)

mul_result = x[:,np.newaxis,:] * y[:,:,np.newaxis]
print('mul_result shape =', mul_result.shape)

mul_result shape = (10, 3, 2)
mul_result shape = (10, 2, 3)
